### ISSUE TITLE
Make the experimental checks optional, turned off by default

### ISSUE THREAD

**Issue by neilb** [charsbar/App-CPANTS-Lint#2]
Hi Ishigaki-san,

How about adding an option:

```
experimental => 0 | 1
```

With the default being false. This would control whether experimental checks are done / reported.

Cheers,
Neil

**Comment by charsbar** [comment]
Thanks! That was an undocumented option in cpants_lint.pl I forgot to implement. Fixed in  3568ed8ada00a906ea02f49b04cd7399a726eff5.
