### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [charsbar/App-CPANTS-Lint#4]
Seems you've released new 0.05 to CPAN but there's no corresponding release tag here on github.

Please tag your releases (and remember to push them - i.e. "git push --tags").  That makes it easier to track granular upstream changes for distributors (like Debian where I help maintain the (re)distribution of App-CPANTS-Lint).

**Comment by charsbar** [comment]
done. thanks for the nudge.

**Comment by jonassmedegaard** [comment]
wauw, that was fast :-)
